database:
  # MongoDB database connection string
  # Example format: mongodb://username:password@host:port/dbName?tls=true
  # NOTE: The connection string must be URI-encoded
  # NOTE: Change the dbName if you want to use a database having a custom name
  mongodb-connection-string: ""

antiSpoofing:
  # If enabled, players having similar name cannot join the server
  # Example: xXxPlayerxXx is similar to xxxplAYerxxX so if either of these usernames joins the server first
  # the remaining username will not be allowed to connect to the server
  enabled: false

messages:
  ban: "You have been permanently banned from this server. Reason: {reason}"
  tempBan: "You have been banned from this server for {duration}. Reason: {reason}. You will be automatically unbanned on {unbanDate}"
  kick: "You have been kicked from this server. Reason: {reason}"
  kickFailed: "You cannot kick an offline player"
  mute: "You have been permanently muted. Reason: {reason}"
  playerBanned: "Player {player} has been banned"
  cannotBanSelf: "You cannot ban yourself"
  noReason: "No reason provided"
  invalidDur: "Invalid Duration"
  alreadyBanned: "Player {player} is already banned"
  noRecord: "No records for {} found"
  commandUsage: "Invalid command usage"
  invalidCommand: "Command does not exist"
  unbanned: "Player {player} unbanned"
  tempMute: "You have been muted for {duration}. Reason: {reason}. You will be automatically unmuted on {unmuteDate}"
  cannotMuteSelf: "You cannot mute yourself"
  alreadyMuted: "Player {player} is already muted"
  playerMuted: "Player {player} is muted"
  unmuted: "Player {player} unmuted"
  playerExist: "Your account already exists."
